### PR TITLE
Removed heavy fallback

### LINKED ISSUE #1: Too big
I feel that if you're going to provide querySelectorAll fallback you might as well just use `qwery`.

`dom-select` currently compiles to 15kB and that kinda defeats the purpose.

### PR DESCRIPTION
**Pull request by fregante**
Otherwise there's no point in using this over `qwery` directly, which uses the same interface.

Fixes #1

### CODE REVIEW

**Comment by azer** [comment]
how about making this a new module ?

**Comment by fregante** [comment]
I could I'm all for improving existing stuff instead of duplicating it. :)

Semver should guarantee that people with the current 0.0.0 version will stay compatible with... gasp... IE7, while everybody else benefits.

Yeah, I forgot that IE8 actually supports qSA so this would make it IE8+, not IE9+ like I mentioned in my commit.

**Comment by azer** [comment]
Makes sense, removed the fallback & released 1.0.1. Thanks for the PR!

**Comment by fregante** [comment]
Why not just accept my PR? I had made adjustments to package.json as well

**Comment by azer** [comment]
@bfred-it I didn't understand why you removed the main field, that's why moved changes manually

**Comment by fregante** [comment]
The main field is to be used only in case the main file isn't index.js; that's already the main file.

**Comment by azer** [comment]
@bfred-it I didn't know that honestly :)

**Comment by fregante** [comment]
No worries, I only learned that last week :D

**Pull request closed without merging**
